#!/bin/bash/
#years='2010 2011 2012 2013 2014 2015 2016 2017 2018'
#for year in $years
#do
#sbatch job.sbatch $year
#done

i=201840

while [ $i -lt 201853 ]
do
echo $i
sbatch job.sbatch $i
i=$(($i+1))
done

j=201901
while [ $j -lt 201921 ]
do
echo $j
sbatch job.sbatch $j
j=$(($j+1))
done
