#!/bin/bash/
#years='2010 2011 2012 2013 2014 2015 2016 2017 2018'
#for year in $years
#do
#sbatch job.sbatch $year
#done


folder=dump/
year=2017
i=$((year))40

while [ $i -lt $((year))53 ]
do
echo $i
sbatch job.sbatch $i
i=$(($i+1))
done

j=$((year+1))01
while [ $j -lt $((year+1))21 ]
do
echo $j
sbatch job.sbatch $j
j=$(($j+1))
done

#. R_load
#varibs=ght
#input_filename=${varibs}_exog/
#score_filename=scores_$((year))_$varibs.csv 
#Rscript ${folder}score_submission.R $year input_filename $score_filename
