#!/bin/bash/
#years='2010 2011 2012 2013 2014 2015 2016 2017 2018'
#for year in $years
#do
#sbatch job.sbatch $year
#done
#source ./R_load.sh
varibs=state
out_folder=dump/${varibs}_exog/
years="2017 2018"
for year in $years
do
i=$((year))40
out_file=${out_folder}/${year}/
score_filename=scores_$((year))_$varibs.csv 

while [ $i -lt $((year))53 ]
do
echo $i
sh job.sh $i $out_file
i=$(($i+1))
done

j=$((year+1))01
while [ $j -lt $((year+1))21 ]
do
echo $j
sh job.sh $j $out_file
j=$(($j+1))
done


#Rscript score_submission.R $year $out_folder $score_filename
done
